// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsjbhdwkd2mRh3K_PLxuAHGUGwI69KDOI',
    appId: '1:162507650416:web:428d9d47ca1f7bc7b04bb5',
    messagingSenderId: '162507650416',
    projectId: 'taller-universidades',
    authDomain: 'taller-universidades.firebaseapp.com',
    storageBucket: 'taller-universidades.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjCb70lHiFICH87PURm-bcTX8Ii1Hzvo',
    appId: '1:162507650416:android:83a9e82942a07aacb04bb5',
    messagingSenderId: '162507650416',
    projectId: 'taller-universidades',
    storageBucket: 'taller-universidades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxgo0v5WJJTwrCkqrzaQWRimTnwTzotT0',
    appId: '1:162507650416:ios:469c3cdeea06be14b04bb5',
    messagingSenderId: '162507650416',
    projectId: 'taller-universidades',
    storageBucket: 'taller-universidades.firebasestorage.app',
    iosBundleId: 'com.example.tallerFirebaseUniversidades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxgo0v5WJJTwrCkqrzaQWRimTnwTzotT0',
    appId: '1:162507650416:ios:469c3cdeea06be14b04bb5',
    messagingSenderId: '162507650416',
    projectId: 'taller-universidades',
    storageBucket: 'taller-universidades.firebasestorage.app',
    iosBundleId: 'com.example.tallerFirebaseUniversidades',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsjbhdwkd2mRh3K_PLxuAHGUGwI69KDOI',
    appId: '1:162507650416:web:2dea013de0e557dfb04bb5',
    messagingSenderId: '162507650416',
    projectId: 'taller-universidades',
    authDomain: 'taller-universidades.firebaseapp.com',
    storageBucket: 'taller-universidades.firebasestorage.app',
  );
}
